package com.cvscreening.persistence;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Nang cap DB CU (do Hibernate ddl-auto: update tao, chua co Flyway) len schema moi ma khong mat du lieu.
 * Day la tinh huong cua moi may dev da tung chay backend truoc khi co Flyway.
 */
@Testcontainers(disabledWithoutDocker = true)
class LegacySchemaMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    /** Schema theo dung phong cach Hibernate 6 sinh ra: constraint ten ngau nhien / ten mac dinh cua PG. */
    private static final String LEGACY_DDL = """
            create table users (created_at timestamp(6) with time zone not null, id bigint generated by default as identity,
                email varchar(255) not null unique, full_name varchar(255) not null, password varchar(255) not null,
                role varchar(255) not null check (role in ('HR','CANDIDATE')), primary key (id));
            create table jobs (active boolean not null, created_at timestamp(6) with time zone not null,
                created_by bigint not null, id bigint generated by default as identity, description TEXT not null,
                location varchar(255), required_skills TEXT not null, title varchar(255) not null, primary key (id));
            create table cvs (candidate_id bigint not null, id bigint generated by default as identity,
                job_id bigint not null, uploaded_at timestamp(6) with time zone not null, file_name varchar(255) not null,
                s3key varchar(255) not null, status varchar(255) not null check (status in ('PENDING','PROCESSED','FAILED')),
                review_status varchar(255) check (review_status in ('NEW','SHORTLISTED','REJECTED')), primary key (id));
            alter table if exists cvs add constraint UKjf1ex4xq8b4b0pvmwsgl9lixy unique (candidate_id, job_id);
            create table match_results (score float(53) not null, years_experience integer,
                created_at timestamp(6) with time zone not null, cv_id bigint not null unique, id bigint generated by default as identity,
                job_id bigint not null, matched_skills TEXT, missing_skills TEXT, summary TEXT, primary key (id));
            """;

    private static final String LEGACY_DATA = """
            insert into users (created_at, email, full_name, password, role) values
                (now(), ' HR@Demo.com ', 'HR', 'h', 'HR'), (now(), 'candidate@demo.com', 'UV', 'h', 'CANDIDATE');
            insert into jobs (active, created_at, created_by, description, required_skills, title)
                values (true, now(), 1, 'd', 'Java', 'Java Dev');
            insert into cvs (candidate_id, job_id, uploaded_at, file_name, s3key, status, review_status)
                values (2, 1, now(), 'cv.pdf', 'cvs/a.pdf', 'PROCESSED', null);
            insert into match_results (score, created_at, cv_id, job_id) values (80, now(), 1, 1);
            -- ket qua mo coi: job_id lech voi job cua CV (du lieu ban con sot tu truoc)
            insert into match_results (score, created_at, cv_id, job_id) values (50, now(), 99, 1);
            """;

    @BeforeEach
    void resetSchema() throws SQLException {
        try (Connection c = connect(); Statement s = c.createStatement()) {
            s.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;");
        }
    }

    @Test
    void dbCuCuaHibernate_nangCapGiuDuLieu_vaChuanHoaConstraint() throws SQLException {
        try (Connection c = connect(); Statement s = c.createStatement()) {
            s.execute(LEGACY_DDL);
            s.execute(LEGACY_DATA);
        }

        var result = flyway().migrate();

        assertTrue(result.success);
        try (Connection c = connect(); Statement s = c.createStatement()) {
            assertEquals("hr@demo.com", single(s, "SELECT email FROM users WHERE id = 1"));
            assertEquals("NEW", single(s, "SELECT review_status FROM cvs WHERE id = 1"));
            assertEquals("1", single(s, "SELECT count(*) FROM match_results"), "ket qua mo coi phai bi xoa");
            assertEquals("80", single(s, "SELECT score::int FROM match_results"));

            List<String> constraints = list(s, """
                    SELECT conname FROM pg_constraint
                    WHERE conrelid IN ('users'::regclass, 'cvs'::regclass, 'match_results'::regclass, 'jobs'::regclass)
                      AND contype IN ('u', 'c', 'f')
                    """);
            assertTrue(constraints.containsAll(List.of("uk_users_email", "uk_cvs_candidate_job",
                    "uk_match_results_cv", "fk_cvs_job", "fk_match_results_cv_job")), constraints.toString());
            assertTrue(constraints.stream().noneMatch(n -> n.startsWith("UK") || n.endsWith("_key")),
                    "constraint ten ngau nhien cua Hibernate phai bi go: " + constraints);
        }
    }

    @Test
    void dbMoiTinh_migrateTuDau() throws SQLException {
        var result = flyway().migrate();

        assertTrue(result.success);
        assertEquals(3, result.migrationsExecuted);
        try (Connection c = connect(); Statement s = c.createStatement()) {
            assertEquals("0", single(s, "SELECT count(*) FROM outbox_messages"));
            // V3: bang tu dien ky nang rong cho toi khi AI worker dong bo
            assertEquals("0", single(s, "SELECT count(*) FROM skill_keywords"));
        }
    }

    private static Flyway flyway() {
        return Flyway.configure()
                .dataSource(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .load();
    }

    private static Connection connect() throws SQLException {
        return DriverManager.getConnection(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
    }

    private static String single(Statement s, String sql) throws SQLException {
        try (ResultSet rs = s.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getString(1);
        }
    }

    private static List<String> list(Statement s, String sql) throws SQLException {
        List<String> values = new ArrayList<>();
        try (ResultSet rs = s.executeQuery(sql)) {
            while (rs.next()) {
                values.add(rs.getString(1));
            }
        }
        return values;
    }
}
