-- V1: schema goc, trung khop voi schema ma Hibernate (ddl-auto: update) tung tu sinh.
-- Dung IF NOT EXISTS de chay an toan tren ca 2 truong hop:
--   * DB moi tinh      -> tao bang
--   * DB cu cua dev     -> bang da ton tai, khong dung vao du lieu (V2 se chuan hoa constraint)

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    description      TEXT NOT NULL,
    required_skills  TEXT NOT NULL,
    location         VARCHAR(255),
    created_by       BIGINT NOT NULL,
    active           BOOLEAN NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS cvs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name     VARCHAR(255) NOT NULL,
    s3key         VARCHAR(255) NOT NULL,
    status        VARCHAR(255) NOT NULL,
    candidate_id  BIGINT NOT NULL,
    job_id        BIGINT NOT NULL,
    uploaded_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS match_results (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_id             BIGINT NOT NULL,
    job_id            BIGINT NOT NULL,
    score             DOUBLE PRECISION NOT NULL,
    matched_skills    TEXT,
    missing_skills    TEXT,
    summary           TEXT,
    years_experience  INTEGER,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
