-- V2: toan ven du lieu + hieu nang + audit + transactional outbox.

-- 1) Go cac constraint UNIQUE/CHECK/FK ma Hibernate tu sinh voi ten ngau nhien (vd UK6dotkott2kjsp8vw4d0m25fb7).
--    Code bat loi theo TEN constraint (DbConstraints) nen moi constraint phai co ten co dinh, tao lai ben duoi.
--    DB moi tinh tu V1 khong co constraint nao -> vong lap khong lam gi.
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT c.conrelid::regclass AS tbl, c.conname
        FROM pg_constraint c
        WHERE c.contype IN ('u', 'c', 'f')
          AND c.conrelid IN ('users'::regclass, 'jobs'::regclass, 'cvs'::regclass, 'match_results'::regclass)
    LOOP
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.tbl, r.conname);
    END LOOP;
END $$;

-- 2) users: email chuan hoa (trim + chu thuong) truoc khi dat unique -> "A@x.com" va "a@x.com" la mot
UPDATE users SET email = lower(trim(email));
ALTER TABLE users
    ADD CONSTRAINT uk_users_email UNIQUE (email),
    ADD CONSTRAINT ck_users_role CHECK (role IN ('HR', 'CANDIDATE')),
    ADD CONSTRAINT ck_users_email_normalized CHECK (email = lower(trim(email)));

-- 3) jobs
ALTER TABLE jobs
    ADD CONSTRAINT fk_jobs_created_by FOREIGN KEY (created_by) REFERENCES users (id);
CREATE INDEX IF NOT EXISTS idx_jobs_created_by ON jobs (created_by, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_active_created ON jobs (created_at DESC) WHERE active;

-- 4) cvs: trang thai xet duyet cua HR (NOT NULL, bo hack nullable) + audit ai/khi nao xet duyet
ALTER TABLE cvs ADD COLUMN IF NOT EXISTS review_status VARCHAR(255);
UPDATE cvs SET review_status = 'NEW' WHERE review_status IS NULL;
ALTER TABLE cvs
    ALTER COLUMN review_status SET DEFAULT 'NEW',
    ALTER COLUMN review_status SET NOT NULL,
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS reviewed_by BIGINT;

ALTER TABLE cvs
    ADD CONSTRAINT ck_cvs_status CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED')),
    ADD CONSTRAINT ck_cvs_review_status CHECK (review_status IN ('NEW', 'SHORTLISTED', 'REJECTED')),
    -- Moi ung vien chi nop 1 CV cho 1 tin
    ADD CONSTRAINT uk_cvs_candidate_job UNIQUE (candidate_id, job_id),
    -- Dich cua FK kep tu match_results (bao dam match_results.job_id luon khop voi cvs.job_id)
    ADD CONSTRAINT uk_cvs_id_job UNIQUE (id, job_id),
    ADD CONSTRAINT fk_cvs_candidate FOREIGN KEY (candidate_id) REFERENCES users (id),
    ADD CONSTRAINT fk_cvs_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    ADD CONSTRAINT fk_cvs_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (id);
-- uk_cvs_candidate_job chi giup tim theo candidate_id; truy van cua HR loc theo job_id
CREATE INDEX IF NOT EXISTS idx_cvs_job ON cvs (job_id, uploaded_at DESC);

-- 5) match_results: 1 ket qua / CV, job_id bat buoc khop voi job cua CV
DELETE FROM match_results m
WHERE NOT EXISTS (SELECT 1 FROM cvs c WHERE c.id = m.cv_id AND c.job_id = m.job_id);
ALTER TABLE match_results
    ADD CONSTRAINT uk_match_results_cv UNIQUE (cv_id),
    ADD CONSTRAINT ck_match_results_score CHECK (score BETWEEN 0 AND 100),
    ADD CONSTRAINT fk_match_results_cv_job FOREIGN KEY (cv_id, job_id)
        REFERENCES cvs (id, job_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_match_results_job ON match_results (job_id);

-- 6) Transactional outbox: message cho AI worker duoc ghi CUNG transaction voi ban ghi CV,
--    OutboxRelay doc cac dong da commit roi moi day sang SQS.
CREATE TABLE outbox_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id  BIGINT NOT NULL,
    payload       TEXT NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    sent_at       TIMESTAMP(6) WITH TIME ZONE,
    attempts      INTEGER NOT NULL DEFAULT 0,
    last_error    TEXT
);
CREATE INDEX idx_outbox_unsent ON outbox_messages (id) WHERE sent_at IS NULL;
CREATE INDEX idx_outbox_sent_at ON outbox_messages (sent_at) WHERE sent_at IS NOT NULL;
